[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = "0.8.20"
# EVM version must be Paris not Shanghai to prevent PUSH0 incompatibility with other EVM L1s
evm_version = "paris"
optimizer_runs = 1_000_000
# via_ir = true

[fmt]
line_length = 160

# See more config options https://github.com/foundry-rs/foundry/tree/master/config