name: Forge Tests

env:
  FOUNDRY_PROFILE: "ci"

on: [push, pull_request]

jobs:
  forge-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        run: forge install
        # NOTE: must run `forge update` explicitly, repo uses cached deps instead of pulling fresh

      - name: Check formatting
        run: forge fmt --check

      - name: Run forge tests
        # env:
        #   ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
        # run: forge test --fork-url "https://eth-mainnet.alchemyapi.io/v2/$ALCHEMY_API_KEY"
        run: forge test --ffi -vvv